# Fabric Properties
	# check these on https://fallen-breath.github.io/fabric-versions/?version=26.2
	minecraft_version=26.2
	parchment_version=
	loom.platform=fabric

# Fabric Mod Metadata
	# https://fabricmc.net/versions.html
	fabric_loader_version=0.19.5
	fabric_minecraft_dependency=>=26.2 <26.3
	forge_minecraft_dependency=[26.2, 26.3)

# Build Information
	# The target mc versions for the mod during mod publishing, separated with \n
	game_versions=26.2
