name: step.matrix_prepare

on:
  workflow_call:
    inputs:
      target_subproject:
        description: see release.yml, for generating matrix entries
        type: string
        required: false
        default: ''
    outputs:
      matrix:
        description: The generated run matrix
        value: ${{ jobs.matrix_prep.outputs.matrix }}


jobs:
  matrix_prep:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Display context
        run: | 
          echo ref_name = ${{ github.ref_name }}
          echo target_subproject = ${{ github.event.inputs.target_subproject }}
          echo target_release_tag = ${{ github.event.inputs.target_release_tag }}

      - id: setmatrix
        run: python3 .github/workflows/scripts/matrix.py  # ubuntu-22.04 uses Python 3.10.6
        env:
          TARGET_SUBPROJECT: ${{ inputs.target_subproject }}

      - name: Print matrix
        run: echo ${{ steps.setmatrix.outputs.matrix }}

    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
